// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Fa6Ski_vOWjQmMJvIUpvkjb7ZZflsFw',
    appId: '1:877730843272:web:3086c913c68976d3ae6d3d',
    messagingSenderId: '877730843272',
    projectId: 'edm-solutions',
    authDomain: 'edm-solutions.firebaseapp.com',
    storageBucket: 'edm-solutions.firebasestorage.app',
    measurementId: 'G-D4970D5FLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVP60uidQqeegbueuhME2kvvT0lbJo-Z8',
    appId: '1:877730843272:android:88e84af8c25c8b17ae6d3d',
    messagingSenderId: '877730843272',
    projectId: 'edm-solutions',
    storageBucket: 'edm-solutions.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo4-wR2399k9k9wUGQUxmc4HRH2DIX90c',
    appId: '1:877730843272:ios:ad7b9c42ff0f3620ae6d3d',
    messagingSenderId: '877730843272',
    projectId: 'edm-solutions',
    storageBucket: 'edm-solutions.firebasestorage.app',
    iosBundleId: 'com.nexus.edmsolutions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo4-wR2399k9k9wUGQUxmc4HRH2DIX90c',
    appId: '1:877730843272:ios:ad7b9c42ff0f3620ae6d3d',
    messagingSenderId: '877730843272',
    projectId: 'edm-solutions',
    storageBucket: 'edm-solutions.firebasestorage.app',
    iosBundleId: 'com.nexus.edmsolutions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1Fa6Ski_vOWjQmMJvIUpvkjb7ZZflsFw',
    appId: '1:877730843272:web:f3224f08365c996eae6d3d',
    messagingSenderId: '877730843272',
    projectId: 'edm-solutions',
    authDomain: 'edm-solutions.firebaseapp.com',
    storageBucket: 'edm-solutions.firebasestorage.app',
    measurementId: 'G-6BSJ4ELQBX',
  );
}
